version: "3"
services:
  nodebb_db:
    image: mongo:3.6
    command: ['mongod', '--auth', '--bind_ip_all']
    networks:
      - nodebb_net   
    volumes:
      - "./dbIniter/:/docker-entrypoint-initdb.d/"
      - "/mnt/data/nodebb:/data/db"
      - "/mnt/backup/nodebb:/backup"
      - "./configs.json:/etc/nodebb/configs.json"
    restart: always
    environment:
     - TZ=Asia/Shanghai
  nodebb:
    image: nodebb/docker
    links: 
      - nodebb_db
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - nodebb_net
      - webgateway
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "traefik.frontend.rule=Host:x.nlinv.com"
      - "traefik.port=4567"
      - "traefik.docker.network=webgateway"
      - "traefik.enable=true"

networks:
 nodebb_net:
  external: true
 webgateway:
   external: true
